# Ajouter une aliments
POST http://localhost:8080/couleur
Content-Type: application/json

{
  "id": 1,
  "nom": "Rouge",
  "hexadecimalRVB": "#FF0000"
}

###

# Obtenir une aliments par ID // ICI PROBLEME
GET http://localhost:8080/couleur/4


###

# Obtenir toutes les alimentss
GET http://localhost:8080/couleur

###

# Modifier une aliments par ID // ICI PROBLEME
PUT http://localhost:8080/couleur/23
Content-Type: application/json

{
  "nom": "NouveauRouge",
  "hexadecimalRVB": "#FF0000"
}

###

# Supprimer une aliments par ID
DELETE http://localhost:8080/couleur/12



############################



# Modifier un aliment par ID // ICI PROBLEME
PUT http://localhost:8080/aliments/1
Content-Type: application/json

{
  "nom": "NouvellePomme",
  "poidsMoyen": 0.1,
  "calories": 60,
  "vitaminesC": 0,
  "typeId": 2,
  "couleurId": 2
}

###

# Obtenir un aliments par ID // ICI PROBLEME
GET http://localhost:8080/aliments/1


###

# Obtenir tout les alimentss
GET http://localhost:8080/aliments

###

# Modifier un aliment par ID  // ICI PROBLEME
PUT http://localhost:8080/aliments/1
Content-Type: application/json

{
  "nom": "NouvellePomme",
  "poidsMoyen": 0.1,
  "calories": 60,
  "vitaminesC": 0,
  "typeId": 2,
  "couleurId": 2
}

###


# Supprimer une aliments par ID  // ICI PROBLEME
DELETE http://localhost:8080/aliments/1